config/routes.rb
Rails.application.routes.draw do
    resources :tasks
    resources :tags
    root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recurring_task_generator.rb
class RecurringTaskGenerator < ApplicationRecord
    belongs_to :task, dependent: :destroy
    validates :last_date, :end_date, :interval, presence: true
    validates :task, presence: true
    validates :end_date_must_be_later_than_last_date
    def end_date_must_be_later_than_last_date
        if last_date.present? && end_date.present? && (last_date > end_date)
            errors.add(:end_date, " must be later than last date.")
        end
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :tasks, -> { distinct }
    validates :name, presence:true
end

app/models/task.rb
class Task < ApplicationRecord
    has_and_belongs_to_many :tags, -> { distinct }
    has_many :recurring_task_generators
    has_one :super_task, class_name: "Task"
    has_many :sub_tasks, class_name: "Task", foreign_key: "parent_id"
    validates :name, :deadline, presence:true
    validates :priority, :inclusion => 1..5, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def index
        @tags = Tag.all
    end

    def show
        @tags = Tag.all
        @selected_tag = Tag.find(params[:id])
        @tasks = @selected_tag.tasks
        render 'tasks/index'
    end

    def new
        @tag = Tag.new
    end

    def edit
        respond_to do |format|
            format.js {}
            format.html
        end
        @tag = Tag.find(params[:id])
    end

    def create
        @tag = Tag.new(tag_params)
        if @tag.save
            redirect_to tasks_path
        else
            render 'new'
        end
    end

    def update
        @tag = Tag.find(params[:id])

        if @tag.update(tag_params)
            redirect_to @tag
        else
            render 'edit'
        end
    end

    def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy

        redirect_to tags_path
    end

    private
        def tag_params
            params.require(:tag).permit(:name)
        end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    def index
        @tasks = Task.all
        @tags = Tag.all
    end

    def show
        @task = Task.find(params[:id])
    end

    def new
        respond_to :html, :js
        @task = Task.new
    end

    def edit
        respond_to :html, :js
        @task = Task.find(params[:id])
    end

    def create
        @task = Task.new(task_params)
        if @task.save
            add_tags @task,
                ActiveSupport::JSON.decode(params[:task][:tags])
            redirect_to @task
        else
            @tasks = Task.all
            @tags = Tag.all
            render 'index'
        end
    end

    def update
        @task = Task.find(params[:id])
        if @task.update(task_params)
            remove_all_tags @task
            add_tags @task,
                ActiveSupport::JSON.decode(params[:task][:tags])
            destroy_unused_tags
            redirect_to @task
        else
            render 'edit'
        end

    end

    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        destroy_unused_tags
        redirect_to tasks_path
    end

    def destroy_unused_tags
        Tag.all.each do |tag|
            if tag.tasks.empty?
                tag.destroy
            end
        end
    end

    def add_tags(task, tags_hash)
        tags_hash.each do |tag_name|
            tag = Tag.find_by name: tag_name
            if (tag)
                task.tags << tag
            else
                task.tags.create('name' => tag_name)
            end
        end
    end

    def get_tags_array
        tags = Tag.all
        # -1 means no tags
        tags_array = [['-', -1]]
        tags.each do |tag|
            tags_array << [tag.name, tag.id]
        end
        return tags_array
    end

    def remove_all_tags(task)
        task.tags.clear
    end

    private
        def task_params
            params.require(:task).permit(:name, :detail, :deadline)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/application/_modal.html.erb
<!-- Button trigger modal
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#popup">
  Launch demo modal
</button>
 -->
<!-- Modal -->
<div class="modal" id="popup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="popupTitle">TITLE</h3>
      </div>
      <div class="modal-body" id="popupBody">
        ...
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'flatpickr' %>
    <%= stylesheet_link_tag    'flatpickr' %>
    <%= yield :head %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
      <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/tasks"> </a>
        </div>
            -->

        <div class="collapse navbar-collapse" id="navbar">
          <ul class="nav navbar-nav">
            <li >
                <%= link_to :Tasks, tasks_path %>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    <%= render 'modal' %>
    <div class="container">
      <%= yield %>
  </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <! IE10 viewport hack for Surface/desktop Windows 8 bug
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
    -->
  </body>
</html>

app/views/tags/_edit.html.erb
<%= form_for :tag, url: tag_path(@tag), method: :patch do |f| %>

  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tag.errors.count, "error") %> prohibited
        this tag from being saved:
      </h2>
      <ul>
        <% @tag.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.text_field :name%>
    <%= submit_tag('Rename', class: 'btn btn-default', id: 'submit') %>
  </p>
<% end %>

app/views/tags/_label.html.erb
<%= content_tag(:span, tag, class: ['tag', 'tag_fixed']) %>

app/views/tags/edit.js.erb
$('#popupTitle').html("Rename Tag");
$('#popupBody').html("<%= j (render 'edit') %>");

app/views/tags/index.html.erb
<h1>All tags</h1>

<% @tags.each do |tag| %>
<p> <%= tag.id %>
    <%= tag.name %></p>
<% end %>

app/views/tags/new.html.erb
<h1>New Tag</h1>
<% if @tag.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@tag.errors.count, "error") %> prohibited
       this tag from being saved:
     </h2>
     <ul>
       <% @tag.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>
<%= form_for :tag, url: tags_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

    <%= f.submit %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for @task, html: {id: "new_task_form"} do |f| %>

   <div class="form-group">
     <%= label_tag(:name) %>
     <span id = "nameError" class="help-inline">
         Please enter name.
     </span><br/>
     <%= f.text_field(:name, class: 'form-control') %>
   </div>
   <div class="form-group">
     <%= label_tag(:detail) %><br/>
     <%= f.text_area(:detail, class: 'form-control') %>
   </div>
   <div class="form-group">
     <%= label_tag(:deadline) %>
     <span id = "deadlineError" class="help-inline">
         Please select deadline.
     </span><br/>
     <%= f.datetime_field(:deadline, id: 'deadline') %>
     <script>    $("#deadline").flatpickr({
        minDate: new Date(),
        enableTime: true
        });
    </script>
   </div>
   <div class="form-group">
     <%= label_tag(:tags) %><br/>
     <span id="tags_display">
         <% @task.tags.each do |tag| %>
            <%= render 'tags/label', tag: tag.name %>
         <% end %>
     </span>
     <%= text_field_tag(:tag_input) %>
     <%= f.text_field(:tags, id: 'tags', type: 'hidden', value: '')%>
   </div>
   <div>
     <%= button_tag('Submit', type: 'submit',
        class: 'btn btn-default btn-primary btn-block', id: 'submit') %>
   </div>
  <script> prepare_form() </script>
<% end %>

app/views/tasks/_table.html.erb
<table class="table post-list">
    <tr>
        <th>Task</th><th>Due date<th>
    </tr>
      <% @tasks = @tasks.order(deadline: :asc) %>
      <% @tasks.each do |task| %>
        <% if task.deadline < DateTime.now %>
            <tr class='danger'>
        <% elsif task.deadline.to_date == Date.today %>
            <tr class='warning'>
        <% else %>
            <tr>
        <% end %>
          <td><%= task.name %></td>
          <td>
              <span class="cell-date">
                <%= task.deadline.to_formatted_s(:short) %>
              </span>
              <span class="cell-action">
                <%= link_to task_path(task), title: 'Show' do %>
                      <i class="fa fa-eye" aria-hidden="true"></i>
                <% end %>
                  &nbsp;
                  <%= link_to edit_task_path(task), remote: true,
                        title: 'Edit', data:{toggle: 'modal', target: '#popup'} do %>
                        <%= content_tag(:i, '', class: 'fa fa-edit',
                            aria: {hidden: 'true'}) %>
                  <% end %>
                  &nbsp;
                  <a title='Delete' href="javascript:;">
                      <%= link_to task_path(task),
                        method: :delete,
                        data: { confirm: 'Do you want to delete this task?' } do %>
                      <i class="fa fa-trash" aria-hidden="true"></i>
                      <% end %>
                  </a>
              </span>
          </td>
        </tr>
      <% end %>
</table>

app/views/tasks/edit.js.erb
$('#popupTitle').html("Edit Task");
$('#popupBody').html("<%= j (render 'form') %>");

app/views/tasks/index.html.erb
<div class="page-header">
    <h1>All tasks</h1>&nbsp;
            <%= link_to new_task_path, remote: true do %>
            <% button_tag(type: 'button', data:{toggle: 'modal',
                target: '#popup'}, class: 'btn btn-default') do %>
                <% content_tag(:i, '', class: 'fa fa-plus',
                    aria: {hidden: 'true'}) %>
                <% end %>
            <% end %>
</div>
<% if defined?(@task) and @task.errors.any? %>
 <div id="error_explanation" class="alert alert-danger" role="alert">
    <p><strong>
       <%= pluralize(@task.errors.count, "error") %> prohibited
       this task from being saved:</strong>
   </p>
     <ul>
       <% @task.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
  </div>
  <hr/>
<% end %>
<!-- Tag buttons -->
<div class="btn-group" role="group" aria-label="">
  <%= link_to 'All', tasks_path, class: "btn btn-default", role: "button", id: "tag-0" %>
  <% @tags.each do |tag| %>
    <% if defined?(@selected_tag) and (tag.id == @selected_tag.id) %>
            <%= link_to edit_tag_path(tag), remote: true, class: "active btn btn-default",
                role: "button", data:{toggle: 'modal',
                    target: '#popup'} do %>
                    <%= tag.name %>
                    <%= content_tag(:i, '', class: 'fa fa-edit',
                        aria: {hidden: 'true'}) %>
            <% end %>
    <% else %>
        <%= link_to tag.name, tag_path(tag), class: "btn btn-default", role: "button",
            id: "tag-#{tag.id}"%>
        <% end %>
  <% end %>
</div>
<hr/>
<%= render "tasks/table" %>

app/views/tasks/new.js.erb
$('#popupTitle').html("New Task");
$('#popupBody').html("<%= j (render 'form') %>");

app/views/tasks/show.html.erb
<div class='page-header'>
    <h1>Task: <%= @task.name %></h1>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3>Due: <%= @task.deadline.to_formatted_s(:long) %></h3>
  </div>
  <div class='panel-body'>
    <p><%= @task.detail %></p>
  </div>
  <div class="panel-footer">
      Tags:
    <% @task.tags.each do |tag| %>
        <%= link_to tag_path(tag) do %>
            <span> <%= tag.name %> </span>
        <% end %>
    <% end %>
  </div>
</div>
<div class='btn-broup' role='group'>
  <%= link_to 'Edit', edit_task_path(@task), remote: true, class: "btn btn-default",
      role: "button", data:{toggle: 'modal', target: '#popup'} %>
  <%= link_to 'Delete', task_path(@task), method: :delete, class: "btn btn-default",
      role: "button", data: { confirm: 'Do you want to delete this task?' } %>
  <%= link_to tasks_path do %>
  <button type='button' class='btn btn-default'>Back</button>
  <% end %>
</div>